services:
  accounts-service:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - bank-db

  bank-db:
    image: postgres:16
    container_name: bank-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "bank-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"