server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: blocker
  consul:
    host: localhost
    port: 8500
    discovery:
      service-name: blocker
    config:
      enabled: true
      prefix: config
      defaultContext: application
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8180/realms/master

