services:
  exchange-service:
    build:
      context: ./exchange
      dockerfile: Dockerfile
    ports:
      - "8084:8084"

  exchange-db:
    image: postgres:16
    container_name: exchange-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "exchange-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"