spring:
  application:
    name: cash
server:
  port: ${SERVER_PORT:8083}

client:
  accounts:
    base-url: http://localhost:8081/accounts/cash
    connect-timeout-ms: 1000
    response-timeout-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
