server:
  port: 8083

spring:
  application:
    name: cash
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: false

client:
  accounts:
    base-url: http://accounts/accounts
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  blocker:
    base-url: http://blocker/blocker
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  notifications:
    base-url: http://notifications/notifications
    connect-timeout-ms: 1000
    response-timeout-ms: 1000

