server:
  port: 8083

spring:
  application:
    name: cash

client:
  accounts:
    base-url: ${CLIENT_ACCOUNTS_URL}
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  blocker:
    base-url: ${CLIENT_BLOCKER_URL}
    connect-timeout-ms: 1000
    response-timeout-ms: 1000
  notifications:
    base-url: ${CLIENT_NOTIFICATIONS_URL}
    connect-timeout-ms: 1000
    response-timeout-ms: 1000

