CREATE TABLE IF NOT EXISTS  "users" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "login" varchar(100) NOT NULL UNIQUE,
                         "password" varchar(100) NOT NULL,
                         "name" varchar(100) NOT NULL,
                         "birthdate" date NOT NULL,
                         "role" varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS  "accounts" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "currency_id" bigint,
                            "user_id" bigint,
                            "value" decimal,
                            "exists" boolean
);

CREATE TABLE IF NOT EXISTS  "currency" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "title" varchar(100) NOT NULL,
                            "name" varchar(100) NOT NULL
);

ALTER TABLE "accounts" ADD FOREIGN KEY ("currency_id") REFERENCES "currency" ("id");
ALTER TABLE "accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

INSERT INTO currency (name, title)
VALUES
    ('Рубль', 'RUB'),
    ('Доллар США', 'USD'),
    ('Китайский юань', 'CNY');