apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer.fullname" . }}
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
  # Note: We process database_url separately below using tpl
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  #URL accounts service
  CLIENT_ACCOUNTS_URL: {{ .Values.config.accounts_url | quote }}
  #URL blocker service
  CLIENT_BLOCKER_URL: {{ .Values.config.blocker_url | quote }}
  #URL notifications service
  CLIENT_NOTIFICATIONS_URL: {{ .Values.config.notifications_url | quote }}
    #URL exchange service
  CLIENT_EXCHANGE_URL: {{ .Values.config.exchange_url | quote }}