services:
  jenkins:
    build: ../ci-cd
    container_name: jenkins
    user: root
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${KUBECONFIG_PATH}:/root/.kube/config

volumes:
  jenkins_home: