apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\Data\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Sat, 18 Oct 2025 14:31:06 MSK
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: cluster_info
    server: https://host.docker.internal:6443
    insecure-skip-tls-verify: true
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 18 Oct 2025 14:31:06 MSK
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\Data\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\Data\.minikube\profiles\minikube\client.key
