server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://localhost:8180/realms/master

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
