CREATE TABLE IF NOT EXISTS  "rates" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "title" varchar(100) NOT NULL UNIQUE,
                            "name" varchar(200) NOT NULL,
                            "value" decimal
);